seedNodes:
  - host: "localhost"
    port: 8001
    id: node1
  - host: "localhost"
    port: 8002
    id: node2
  - host: "localhost"
    port: 8003
    id: node3
localNode:
  host: "localhost"
  port: 8003
  id: node3
workers: 1
secret: "s3cr3t"
logLevel: "ALL"