seedNodes:
  - host: "localhost"
    port: 8002
    id: node2
  - host: "localhost"
    port: 8003
    id: node3
localNode:
  host: "localhost"
  port: 8002
  id: node2
workers: 2
timeout: 60
secret: "s3cr3t"
logLevel: "INFO"