name: actor_system
description: An implementation of the actor model in Dart.
version: 0.1.0
homepage: http://www.github.com/blimster/actor_system

environment:
    sdk: ">=2.13.0 <3.0.0"

dependencies:
    uuid: ^3.0.0
    yaml: ^3.1.0
    logging: ^1.0.0
    stream_channel: ^2.1.1

dev_dependencies:
    test: ^1.6.8
