name: actor_system
description: An implementation of the actor model in the Dart language. An actor processes only one message at a time, even if the processing is asynchronous.
version: 0.2.0
homepage: https://www.github.com/blimster/actor_system

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    async: ^2.10.0
    uuid: ^3.0.0
    yaml: ^3.1.0
    logging: ^1.0.0
    stream_channel: ^2.1.1
    msgpack_dart_with_web: ^1.0.1

dev_dependencies:
    test: ^1.6.8
    lints: ^2.0.1
