name: actor_cluster
description: Connects multiple actor systems into a cluster. Actor systems can run in different isolates and processes.
version: 0.1.0
homepage: https://www.github.com/blimster/actor_system

environment:
    sdk: ">=2.18.0 <3.0.0"

dependencies:
    actor_system:
        #version: ^0.6.0
        path: ../system
    async: ^2.10.0
    uuid: ^3.0.0
    yaml: ^3.1.0
    logging: ^1.0.0
    stream_channel: ^2.1.1
    msgpack_dart: ^1.0.1

dev_dependencies:
    test: ^1.6.8
    lints: ^2.0.1
