name: actor_system
description: An implementation of the actor model in the Dart language. An actor processes only one message at a time, even if the processing is asynchronous.
version: 0.8.1
homepage: https://www.github.com/blimster/actor_system

environment:
    sdk: ">=2.18.0 <4.0.0"

dependencies:
    logging: ^1.0.0
    metrics: ^0.2.2

dev_dependencies:
    test: ^1.6.8
    lints: ^2.0.1
