seedNodes:
  - host: "localhost"
    port: 8001
    id: node1
  - host: "localhost"
    port: 8002
    id: node2
localNode:
  host: "localhost"
  port: 8004
  id: node4
workers: 2
timeout: 60
secret: "s3cr3t"
